-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-03 05:46:37 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Account
    (
     id_account           SERIAL  NOT NULL ,
     "name"                 VARCHAR (255)  NOT NULL ,
     current_balance      NUMERIC (20,2)  NOT NULL ,
     Currency_id_currency INTEGER  NOT NULL ,
     User_id_user         INTEGER  NOT NULL
    )
;

ALTER TABLE Account
    ADD CONSTRAINT Account_PK PRIMARY KEY ( id_account ) ;

CREATE TABLE Budget
    (
     id_budget              SERIAL  NOT NULL ,
     "limit"                  NUMERIC (20,2)  NOT NULL ,
     "start_date"             DATE  NOT NULL ,
     "end"                  DATE  NOT NULL ,
     User_id_user           INTEGER  NOT NULL ,
     Categories_id_category INTEGER  NOT NULL ,
     Currency_id_currency   INTEGER  NOT NULL
    )
;

ALTER TABLE Budget
    ADD CONSTRAINT Budget_PK PRIMARY KEY ( id_budget ) ;

CREATE TABLE Categories
    (
     id_category SERIAL  NOT NULL ,
     "name"        VARCHAR (200)  NOT NULL ,
     "type"        VARCHAR (100)  NOT NULL
    )
;

ALTER TABLE Categories
    ADD CONSTRAINT Categories_PK PRIMARY KEY ( id_category ) ;

CREATE TABLE Currency
    (
     id_currency   SERIAL  NOT NULL ,
     code          CHAR (3)  NOT NULL ,
     "name"          VARCHAR (100)  NOT NULL ,
     exchange_rate NUMERIC (10,4)  NOT NULL
    )
;

ALTER TABLE Currency
    ADD CONSTRAINT Currency_PK PRIMARY KEY ( id_currency ) ;

CREATE TABLE InflationHistory
    (
     id_inflation SERIAL  NOT NULL ,
     rate         NUMERIC (5,2)  NOT NULL ,
     "date"       DATE  NOT NULL
    )
;

ALTER TABLE InflationHistory
    ADD CONSTRAINT InflationHistory_PK PRIMARY KEY ( id_inflation ) ;

CREATE TABLE Notification
    (
     id_notification SERIAL  NOT NULL ,
     "message"         VARCHAR (400)  NOT NULL ,
     "date"          TIMESTAMP (0)  NOT NULL ,
     is_read         CHAR (1)  NOT NULL ,
     User_id_user    INTEGER  NOT NULL
    )
;

ALTER TABLE Notification
    ADD CONSTRAINT Notification_PK PRIMARY KEY ( id_notification ) ;

CREATE TABLE Relation_14
    (
     User_id_user       INTEGER  NOT NULL ,
     UserGroup_id_group INTEGER  NOT NULL
    )
;

ALTER TABLE Relation_14
    ADD CONSTRAINT Relation_14_PK PRIMARY KEY ( User_id_user, UserGroup_id_group ) ;

CREATE TABLE SavingGoal
    (
     id_saving_goal       SERIAL  NOT NULL ,
     "name"                 VARCHAR (200)  NOT NULL ,
     "target"               NUMERIC (20,2)  NOT NULL ,
     current_amount       NUMERIC (20,2)  NOT NULL ,
     time_limit           DATE ,
     User_id_user         INTEGER  NOT NULL ,
     Currency_id_currency INTEGER  NOT NULL
    )
;

ALTER TABLE SavingGoal
    ADD CONSTRAINT SavingGoal_PK PRIMARY KEY ( id_saving_goal ) ;

CREATE TABLE Scheduled_Transaction
    (
     id_schedule_transaction SERIAL  NOT NULL ,
     frequency               VARCHAR (50)  NOT NULL ,
     next_date               DATE  NOT NULL ,
     amount                  NUMERIC (20,2)  NOT NULL ,
     Account_id_account      INTEGER  NOT NULL ,
     Currency_id_currency    INTEGER  NOT NULL ,
     Categories_id_category  INTEGER  NOT NULL
    )
;

ALTER TABLE Scheduled_Transaction
    ADD CONSTRAINT Scheduled_Transaction_PK PRIMARY KEY ( id_schedule_transaction ) ;

CREATE TABLE Transaction
    (
     id_transaction         SERIAL  NOT NULL ,
     amount                 NUMERIC (20,2)  NOT NULL ,
     transaction_date       TIMESTAMP (0)  NOT NULL ,
     "description"            VARCHAR (400) ,
     is_income              CHAR (1)  NOT NULL ,
     Account_id_account     INTEGER  NOT NULL ,
     Categories_id_category INTEGER  NOT NULL ,
     Currency_id_currency   INTEGER  NOT NULL
    )
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_PK PRIMARY KEY ( id_transaction ) ;

CREATE TABLE "User"
    (
     id_user  SERIAL  NOT NULL ,
     email    VARCHAR (255)  NOT NULL ,
     "password" VARCHAR (255)  NOT NULL ,
     "name"     VARCHAR (255)  NOT NULL
    )
;

ALTER TABLE "User"
    ADD CONSTRAINT User_PK PRIMARY KEY ( id_user ) ;

CREATE TABLE UserGroup
    (
     id_group SERIAL  NOT NULL ,
     "name"     VARCHAR (200)  NOT NULL
    )
;

ALTER TABLE UserGroup
    ADD CONSTRAINT UserGroup_PK PRIMARY KEY ( id_group ) ;

ALTER TABLE Account
    ADD CONSTRAINT Account_Currency_FK FOREIGN KEY
    (
     Currency_id_currency
    )
    REFERENCES Currency
    (
     id_currency
    )
;

ALTER TABLE Account
    ADD CONSTRAINT Account_User_FK FOREIGN KEY
    (
     User_id_user
    )
    REFERENCES "User"
    (
     id_user
    )
    ON DELETE CASCADE
;

ALTER TABLE Budget
    ADD CONSTRAINT Budget_Categories_FK FOREIGN KEY
    (
     Categories_id_category
    )
    REFERENCES Categories
    (
     id_category
    )
;

ALTER TABLE Budget
    ADD CONSTRAINT Budget_Currency_FK FOREIGN KEY
    (
     Currency_id_currency
    )
    REFERENCES Currency
    (
     id_currency
    )
;

ALTER TABLE Budget
    ADD CONSTRAINT Budget_User_FK FOREIGN KEY
    (
     User_id_user
    )
    REFERENCES "User"
    (
     id_user
    )
    ON DELETE CASCADE
;

ALTER TABLE Notification
    ADD CONSTRAINT Notification_User_FK FOREIGN KEY
    (
     User_id_user
    )
    REFERENCES "User"
    (
     id_user
    )
    ON DELETE CASCADE
;

ALTER TABLE Relation_14
    ADD CONSTRAINT Relation_14_User_FK FOREIGN KEY
    (
     User_id_user
    )
    REFERENCES "User"
    (
     id_user
    )
;

ALTER TABLE Relation_14
    ADD CONSTRAINT Relation_14_UserGroup_FK FOREIGN KEY
    (
     UserGroup_id_group
    )
    REFERENCES UserGroup
    (
     id_group
    )
;

ALTER TABLE SavingGoal
    ADD CONSTRAINT SavingGoal_Currency_FK FOREIGN KEY
    (
     Currency_id_currency
    )
    REFERENCES Currency
    (
     id_currency
    )
;

ALTER TABLE SavingGoal
    ADD CONSTRAINT SavingGoal_User_FK FOREIGN KEY
    (
     User_id_user
    )
    REFERENCES "User"
    (
     id_user
    )
    ON DELETE CASCADE
;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE Scheduled_Transaction
    ADD CONSTRAINT Scheduled_Transaction_Account_FK FOREIGN KEY
    (
     Account_id_account
    )
    REFERENCES Account
    (
     id_account
    )
;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE Scheduled_Transaction
    ADD CONSTRAINT Scheduled_Transaction_Categories_FK FOREIGN KEY
    (
     Categories_id_category
    )
    REFERENCES Categories
    (
     id_category
    )
;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE Scheduled_Transaction
    ADD CONSTRAINT Scheduled_Transaction_Currency_FK FOREIGN KEY
    (
     Currency_id_currency
    )
    REFERENCES Currency
    (
     id_currency
    )
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_Account_FK FOREIGN KEY
    (
     Account_id_account
    )
    REFERENCES Account
    (
     id_account
    )
    ON DELETE CASCADE
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_Categories_FK FOREIGN KEY
    (
     Categories_id_category
    )
    REFERENCES Categories
    (
     id_category
    )
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_Currency_FK FOREIGN KEY
    (
     Currency_id_currency
    )
    REFERENCES Currency
    (
     id_currency
    )
;



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                         0
-- DROP DATABASE                           0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   3
-- WARNINGS                                 0

INSERT INTO Currency (id_currency, code, "name", exchange_rate)
VALUES (1, 'PLN', 'Złoty', 1.000);

SELECT setval('currency_id_currency_seq', (SELECT MAX(id_currency) FROM Currency));

CREATE OR REPLACE FUNCTION create_def_acc()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO Account (name, current_balance, Currency_id_currency, User_id_user)
    VALUES ('Main Account', 0.00, 1, NEW.id_user);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_create_def_acc
AFTER INSERT ON "User"
FOR EACH ROW
EXECUTE FUNCTION create_def_acc();


INSERT INTO categories (name, "type") VALUES
('Jedzenie i Kawiarnie', 'EXPENSE');

SELECT setval('categories_id_category_seq', (SELECT MAX(id_category) FROM categories));

-- automatic transactions logic
-- imo only logical step is to change structure and add description it does not create any issues so i think its fine
ALTER TABLE scheduled_transaction ADD COLUMN description VARCHAR(255);

CREATE OR REPLACE PROCEDURE catch_up_scheduled_transactions(p_user_id INT)
LANGUAGE plpgsql AS $$
DECLARE
    r_sched RECORD;
    v_is_income CHAR(1);
    v_acc_rate NUMERIC(10,4);
    v_sched_rate NUMERIC(10,4);
    v_converted_amount NUMERIC(20,2);
    v_current_next_date DATE;
    v_final_description VARCHAR(255);
BEGIN
    FOR r_sched IN
        SELECT st.* FROM scheduled_transaction st
        JOIN account a ON st.account_id_account = a.id_account
        WHERE a.user_id_user = p_user_id AND st.next_date <= CURRENT_DATE
    LOOP
        IF r_sched.amount >= 0 THEN
            v_is_income := 'T';
        ELSE
            v_is_income := 'F';
        END IF;
        IF r_sched.description IS NOT NULL AND r_sched.description <> '' THEN
            v_final_description := r_sched.description;
        ELSE
            v_final_description := 'Automatic payment (' || r_sched.frequency || ')';
        END IF;
        SELECT exchange_rate INTO v_acc_rate FROM currency WHERE id_currency = (SELECT currency_id_currency FROM account WHERE id_account = r_sched.account_id_account);
        SELECT exchange_rate INTO v_sched_rate FROM currency WHERE id_currency = r_sched.currency_id_currency;
        v_converted_amount := r_sched.amount * (v_sched_rate / v_acc_rate);
        v_current_next_date := r_sched.next_date;
        WHILE v_current_next_date <= CURRENT_DATE LOOP
            INSERT INTO Transaction (amount, transaction_date, description, is_income, Account_id_account, Categories_id_category, Currency_id_currency)
            VALUES (
                ABS(r_sched.amount),
                v_current_next_date,
                v_final_description,
                v_is_income,
                r_sched.account_id_account,
                r_sched.categories_id_category,
                r_sched.currency_id_currency
            );
            UPDATE Account
            SET current_balance = current_balance + v_converted_amount
            WHERE id_account = r_sched.account_id_account;
            IF UPPER(r_sched.frequency) = 'DAILY' THEN
                v_current_next_date := v_current_next_date + INTERVAL '1 day';
            ELSIF UPPER(r_sched.frequency) = 'WEEKLY' THEN
                v_current_next_date := v_current_next_date + INTERVAL '1 week';
            ELSIF UPPER(r_sched.frequency) = 'MONTHLY' THEN
                v_current_next_date := v_current_next_date + INTERVAL '1 month';
            ELSIF UPPER(r_sched.frequency) = 'YEARLY' THEN
                v_current_next_date := v_current_next_date + INTERVAL '1 year';
            ELSE
                v_current_next_date := v_current_next_date + INTERVAL '1 month';
            END IF;
        END LOOP;
        UPDATE scheduled_transaction
        SET next_date = v_current_next_date
        WHERE id_schedule_transaction = r_sched.id_schedule_transaction;
    END LOOP;
END;
$$;

-- to add cascade delete to scheduled transactions, so when account is deleted, scheduled transactions are also deleted
ALTER TABLE Scheduled_Transaction
    DROP CONSTRAINT IF EXISTS Scheduled_Transaction_Account_FK;

ALTER TABLE Scheduled_Transaction
    ADD CONSTRAINT Scheduled_Transaction_Account_FK FOREIGN KEY ( Account_id_account )
    REFERENCES Account ( id_account )
    ON DELETE CASCADE;

-- view for budget
CREATE OR REPLACE VIEW v_budget_analytics AS
SELECT
    b.id_budget,
    b.limit,
    b.start_date,
    b.end,
    b.user_id_user,
    b.categories_id_category,
    c.name AS category_name,
    b.currency_id_currency,
    curr.code AS currency_code,

    -- Sum of expenses
    COALESCE( -- to make sure we dont get null
        (
            SELECT SUM(t.amount*(curr_trans.exchange_rate/curr_budget.exchange_rate))
            FROM transaction t
            JOIN account a ON t.account_id_account = a.id_account
            JOIN currency curr_trans ON t.currency_id_currency = curr_trans.id_currency
            JOIN currency curr_budget ON curr_budget.id_currency = b.currency_id_currency
            WHERE a.user_id_user = b.user_id_user
              AND t.categories_id_category = b.categories_id_category
              AND t.is_income = 'F'
              AND t.transaction_date >= b.start_date::timestamp
              AND t.transaction_date <= b.end::timestamp
        ), 0.00
    ) AS current_spent,
    -- calculate percentage of budget used to make job of my frontend easier coz it requiers some work
    ROUND((COALESCE(
        (
            SELECT SUM(t.amount*(curr_trans.exchange_rate/curr_budget.exchange_rate))
            FROM transaction t
            JOIN account a ON t.account_id_account = a.id_account
            JOIN currency curr_trans ON t.currency_id_currency = curr_trans.id_currency
            JOIN currency curr_budget ON curr_budget.id_currency = b.currency_id_currency
            WHERE a.user_id_user = b.user_id_user
              AND t.categories_id_category = b.categories_id_category
              AND t.is_income = 'F'
              AND t.transaction_date >= b.start_date::timestamp
              AND t.transaction_date <= b.end::timestamp
        ), 0.00
    ) / b.limit) * 100, 2)::float AS percent_used

FROM budget b
JOIN categories c ON b.categories_id_category = c.id_category
JOIN currency curr ON b.currency_id_currency = curr.id_currency;

--notif logic

CREATE OR REPLACE FUNCTION check_budget_overflow()
RETURNS TRIGGER AS $$
DECLARE
    v_user_id INT;
    v_budget_id INT;
    v_budget_limit NUMERIC(20, 2);
    v_budget_currency_id INT;
    v_current_spent NUMERIC(20, 2);
    v_new_tx_converted NUMERIC(20, 2);
BEGIN
    IF NEW.is_income = 'F' THEN
        SELECT user_id_user INTO v_user_id
        FROM account
        WHERE id_account = NEW.account_id_account;
        SELECT id_budget, "limit", currency_id_currency INTO v_budget_id, v_budget_limit, v_budget_currency_id
        FROM budget
        WHERE user_id_user = v_user_id
          AND categories_id_category = NEW.categories_id_category
          AND NEW.transaction_date >= start_date::timestamp
          AND NEW.transaction_date <= "end"::timestamp;

        IF v_budget_id IS NOT NULL THEN
            SELECT COALESCE(SUM(t.amount * (curr_trans.exchange_rate / curr_budget.exchange_rate)), 0.00) INTO v_current_spent
            FROM transaction t
            JOIN account a ON t.account_id_account = a.id_account
            JOIN currency curr_trans ON t.currency_id_currency = curr_trans.id_currency
            JOIN currency curr_budget ON curr_budget.id_currency = v_budget_currency_id
            WHERE a.user_id_user = v_user_id
              AND t.categories_id_category = NEW.categories_id_category
              AND t.is_income = 'F'
              AND t.transaction_date >= (SELECT start_date FROM budget WHERE id_budget = v_budget_id)::timestamp
              AND t.transaction_date <= (SELECT "end" FROM budget WHERE id_budget = v_budget_id)::timestamp;

            SELECT (NEW.amount * (curr_trans.exchange_rate / curr_budget.exchange_rate)) INTO v_new_tx_converted
            FROM currency curr_trans, currency curr_budget
            WHERE curr_trans.id_currency = NEW.currency_id_currency
              AND curr_budget.id_currency = v_budget_currency_id;

            IF v_current_spent > v_budget_limit AND (v_current_spent - COALESCE(v_new_tx_converted, 0)) <= v_budget_limit THEN
                INSERT INTO notification (message, "date", is_read, user_id_user)
                VALUES (
                    'Limit surpassed. Current spending is: ' || v_current_spent || ' while limit is: ' || v_budget_limit || ' (Percentage used: ' || ROUND((v_current_spent / v_budget_limit) * 100, 2) || '%)',
                    NOW(),
                    'F',
                    v_user_id
                );
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_budget_overflow ON transaction;
CREATE TRIGGER trg_check_budget_overflow
AFTER INSERT ON transaction
FOR EACH ROW
EXECUTE FUNCTION check_budget_overflow();

-- saving goals logic and fixes

ALTER TABLE SavingGoal ADD COLUMN start_date DATE DEFAULT CURRENT_DATE NOT NULL;

-- for Enable Banking integration, we will add a new column to store the external transaction ID from the bank API. This will help us avoid duplicate transactions when syncing with the bank.
ALTER TABLE transaction ADD COLUMN external_id VARCHAR(255);

CREATE UNIQUE INDEX ux_transaction_account_external_id
ON transaction (account_id_account, external_id)
WHERE external_id IS NOT NULL;


-- New table to store bank connection information for each user. This will allow us to manage multiple bank connections per user and handle session management for syncing transactions.
CREATE TABLE bank_connection (
    id_connection SERIAL PRIMARY KEY,
    user_id_user INTEGER NOT NULL REFERENCES "User"(id_user) ON DELETE CASCADE,
    bank_name VARCHAR(100),
    session_id VARCHAR(255) NOT NULL,
    valid_until TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Add a foreign key to the Account table to link it to the bank_connection table. This will allow us to associate each account with a specific bank connection.
ALTER TABLE Account
    ADD COLUMN bank_connection_id INTEGER REFERENCES bank_connection(id_connection) ON DELETE SET NULL,
    ADD COLUMN bank_account_uid VARCHAR(255);


-- Add a unique constraint to ensure that each bank account UID is unique across all accounts. This will help prevent duplicate accounts from being created when syncing with the bank.
ALTER TABLE Account
    ADD CONSTRAINT uq_bank_account_uid UNIQUE (bank_account_uid);

-- Create an index on the bank_connection_id column in the Account table to improve query performance when filtering or joining on this column.
CREATE INDEX idx_account_bank_connection
    ON Account (bank_connection_id);

ALTER TABLE bank_connection ALTER COLUMN valid_until TYPE TIMESTAMPTZ;