-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-03 05:46:37 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Account 
    ( 
     id_account           SERIAL  NOT NULL , 
     "name"                 VARCHAR (255)  NOT NULL , 
     current_balance      NUMERIC (20,2)  NOT NULL , 
     Currency_id_currency INTEGER  NOT NULL , 
     User_id_user         INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Account 
    ADD CONSTRAINT Account_PK PRIMARY KEY ( id_account ) ;

CREATE TABLE Budget 
    ( 
     id_budget              SERIAL  NOT NULL , 
     "limit"                  NUMERIC (20,2)  NOT NULL , 
     "start_date"             DATE  NOT NULL , 
     "end"                  DATE  NOT NULL , 
     User_id_user           INTEGER  NOT NULL , 
     Categories_id_category INTEGER  NOT NULL , 
     Currency_id_currency   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Budget 
    ADD CONSTRAINT Budget_PK PRIMARY KEY ( id_budget ) ;

CREATE TABLE Categories 
    ( 
     id_category SERIAL  NOT NULL , 
     "name"        VARCHAR (200)  NOT NULL , 
     "type"        VARCHAR (100)  NOT NULL 
    ) 
;

ALTER TABLE Categories 
    ADD CONSTRAINT Categories_PK PRIMARY KEY ( id_category ) ;

CREATE TABLE Currency 
    ( 
     id_currency   SERIAL  NOT NULL , 
     code          CHAR (3)  NOT NULL , 
     "name"          VARCHAR (100)  NOT NULL , 
     exchange_rate NUMERIC (10,4)  NOT NULL 
    ) 
;

ALTER TABLE Currency 
    ADD CONSTRAINT Currency_PK PRIMARY KEY ( id_currency ) ;

CREATE TABLE InflationHistory 
    ( 
     id_inflation SERIAL  NOT NULL , 
     rate         NUMERIC (5,2)  NOT NULL , 
     "date"       DATE  NOT NULL 
    ) 
;

ALTER TABLE InflationHistory 
    ADD CONSTRAINT InflationHistory_PK PRIMARY KEY ( id_inflation ) ;

CREATE TABLE Notification 
    ( 
     id_notification SERIAL  NOT NULL , 
     "message"         VARCHAR (400)  NOT NULL , 
     "date"          TIMESTAMP (0)  NOT NULL , 
     is_read         CHAR (1)  NOT NULL , 
     User_id_user    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Notification 
    ADD CONSTRAINT Notification_PK PRIMARY KEY ( id_notification ) ;

CREATE TABLE Relation_14 
    ( 
     User_id_user       INTEGER  NOT NULL , 
     UserGroup_id_group INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Relation_14 
    ADD CONSTRAINT Relation_14_PK PRIMARY KEY ( User_id_user, UserGroup_id_group ) ;

CREATE TABLE SavingGoal 
    ( 
     id_saving_goal       SERIAL  NOT NULL , 
     "name"                 VARCHAR (200)  NOT NULL , 
     "target"               NUMERIC (20,2)  NOT NULL , 
     current_amount       NUMERIC (20,2)  NOT NULL , 
     time_limit           DATE , 
     User_id_user         INTEGER  NOT NULL , 
     Currency_id_currency INTEGER  NOT NULL 
    ) 
;

ALTER TABLE SavingGoal 
    ADD CONSTRAINT SavingGoal_PK PRIMARY KEY ( id_saving_goal ) ;

CREATE TABLE Scheduled_Transaction 
    ( 
     id_schedule_transaction SERIAL  NOT NULL , 
     frequency               VARCHAR (50)  NOT NULL , 
     next_date               DATE  NOT NULL , 
     amount                  NUMERIC (20,2)  NOT NULL , 
     Account_id_account      INTEGER  NOT NULL , 
     Currency_id_currency    INTEGER  NOT NULL , 
     Categories_id_category  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Scheduled_Transaction 
    ADD CONSTRAINT Scheduled_Transaction_PK PRIMARY KEY ( id_schedule_transaction ) ;

CREATE TABLE Transaction 
    ( 
     id_transaction         SERIAL  NOT NULL , 
     amount                 NUMERIC (20,2)  NOT NULL , 
     transaction_date       TIMESTAMP (0)  NOT NULL , 
     "description"            VARCHAR (400) , 
     is_income              CHAR (1)  NOT NULL , 
     Account_id_account     INTEGER  NOT NULL , 
     Categories_id_category INTEGER  NOT NULL , 
     Currency_id_currency   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Transaction 
    ADD CONSTRAINT Transaction_PK PRIMARY KEY ( id_transaction ) ;

CREATE TABLE "User" 
    ( 
     id_user  SERIAL  NOT NULL , 
     email    VARCHAR (255)  NOT NULL , 
     "password" VARCHAR (255)  NOT NULL , 
     "name"     VARCHAR (255)  NOT NULL 
    ) 
;

ALTER TABLE "User" 
    ADD CONSTRAINT User_PK PRIMARY KEY ( id_user ) ;

CREATE TABLE UserGroup 
    ( 
     id_group SERIAL  NOT NULL , 
     "name"     VARCHAR (200)  NOT NULL
    ) 
;

ALTER TABLE UserGroup 
    ADD CONSTRAINT UserGroup_PK PRIMARY KEY ( id_group ) ;

ALTER TABLE Account 
    ADD CONSTRAINT Account_Currency_FK FOREIGN KEY 
    ( 
     Currency_id_currency
    ) 
    REFERENCES Currency 
    ( 
     id_currency
    ) 
;

ALTER TABLE Account 
    ADD CONSTRAINT Account_User_FK FOREIGN KEY 
    ( 
     User_id_user
    ) 
    REFERENCES "User" 
    ( 
     id_user
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Budget 
    ADD CONSTRAINT Budget_Categories_FK FOREIGN KEY 
    ( 
     Categories_id_category
    ) 
    REFERENCES Categories 
    ( 
     id_category
    ) 
;

ALTER TABLE Budget 
    ADD CONSTRAINT Budget_Currency_FK FOREIGN KEY 
    ( 
     Currency_id_currency
    ) 
    REFERENCES Currency 
    ( 
     id_currency
    ) 
;

ALTER TABLE Budget 
    ADD CONSTRAINT Budget_User_FK FOREIGN KEY 
    ( 
     User_id_user
    ) 
    REFERENCES "User" 
    ( 
     id_user
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Notification 
    ADD CONSTRAINT Notification_User_FK FOREIGN KEY 
    ( 
     User_id_user
    ) 
    REFERENCES "User" 
    ( 
     id_user
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Relation_14 
    ADD CONSTRAINT Relation_14_User_FK FOREIGN KEY 
    ( 
     User_id_user
    ) 
    REFERENCES "User" 
    ( 
     id_user
    ) 
;

ALTER TABLE Relation_14 
    ADD CONSTRAINT Relation_14_UserGroup_FK FOREIGN KEY 
    ( 
     UserGroup_id_group
    ) 
    REFERENCES UserGroup 
    ( 
     id_group
    ) 
;

ALTER TABLE SavingGoal 
    ADD CONSTRAINT SavingGoal_Currency_FK FOREIGN KEY 
    ( 
     Currency_id_currency
    ) 
    REFERENCES Currency 
    ( 
     id_currency
    ) 
;

ALTER TABLE SavingGoal 
    ADD CONSTRAINT SavingGoal_User_FK FOREIGN KEY 
    ( 
     User_id_user
    ) 
    REFERENCES "User" 
    ( 
     id_user
    ) 
    ON DELETE CASCADE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Scheduled_Transaction 
    ADD CONSTRAINT Scheduled_Transaction_Account_FK FOREIGN KEY 
    ( 
     Account_id_account
    ) 
    REFERENCES Account 
    ( 
     id_account
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Scheduled_Transaction 
    ADD CONSTRAINT Scheduled_Transaction_Categories_FK FOREIGN KEY 
    ( 
     Categories_id_category
    ) 
    REFERENCES Categories 
    ( 
     id_category
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Scheduled_Transaction 
    ADD CONSTRAINT Scheduled_Transaction_Currency_FK FOREIGN KEY 
    ( 
     Currency_id_currency
    ) 
    REFERENCES Currency 
    ( 
     id_currency
    ) 
;

ALTER TABLE Transaction 
    ADD CONSTRAINT Transaction_Account_FK FOREIGN KEY 
    ( 
     Account_id_account
    ) 
    REFERENCES Account 
    ( 
     id_account
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE Transaction 
    ADD CONSTRAINT Transaction_Categories_FK FOREIGN KEY 
    ( 
     Categories_id_category
    ) 
    REFERENCES Categories 
    ( 
     id_category
    ) 
;

ALTER TABLE Transaction 
    ADD CONSTRAINT Transaction_Currency_FK FOREIGN KEY 
    ( 
     Currency_id_currency
    ) 
    REFERENCES Currency 
    ( 
     id_currency
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                         0
-- DROP DATABASE                           0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   3
-- WARNINGS                                 0

INSERT INTO Currency (id_currency, code, "name", exchange_rate)
VALUES (1, 'PLN', 'Złoty', 1.000);

SELECT setval('currency_id_currency_seq', (SELECT MAX(id_currency) FROM Currency));

CREATE OR REPLACE FUNCTION create_def_acc()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO Account (name, current_balance, Currency_id_currency, User_id_user)
    VALUES ('Main Account', 0.00, 1, NEW.id_user);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_create_def_acc
AFTER INSERT ON "User"
FOR EACH ROW
EXECUTE FUNCTION create_def_acc();


INSERT INTO categories (name, "type") VALUES 
('Jedzenie i Kawiarnie', 'EXPENSE');

SELECT setval('categories_id_category_seq', (SELECT MAX(id_category) FROM categories));